version: "3.10"
services:
  script:
      build:
        context: ./stock-ticker
        dockerfile: Dockerfile
      network_mode: "host"
  fastapi:
    build:
      context: ./stock-retriever-api
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    network_mode: "host"
  